#!/bin/sh

export MSANDERHOME="$(dirname "$(cd "$(dirname "$0")" && pwd)")"
if [ `uname -s|awk '{print $1}'` != "Darwin" ]; then
    if [ -z "${LD_LIBRARY_PATH}" ]; then
       export LD_LIBRARY_PATH="${MSANDERHOME}/lib"
    else
       export LD_LIBRARY_PATH="${MSANDERHOME}/lib:${LD_LIBRARY_PATH}"
    fi
fi

$MSANDERHOME/bin/x/REPLACE_ME $*
