#!/bin/sh

export NABHOME="$(dirname "$(cd "$(dirname "$0")" && pwd)")"
if [ `uname -s|awk '{print $1}'` != "Darwin" ]; then
    if [ -z "${LD_LIBRARY_PATH}" ]; then
       export LD_LIBRARY_PATH="${NABHOME}/lib"
    else
       export LD_LIBRARY_PATH="${NABHOME}/lib:${LD_LIBRARY_PATH}"
    fi
fi

$NABHOME/bin/x/REPLACE_ME $*
