#!/usr/bin/env perl

#  convert shifts output (with the -details option) to an rdb file

print "resname\tres\tatomname\tDA\tDA6\tDG\tDG6\tDT\tDC\n";
print "4\t4N\t6\t8N\t8N\t8N\t8N\t8N\t8N\n";

open OUT, ">fozzoup";

while(<>){

	next unless /^Detailed contributions/;

	$rcur{"DA"} = $rcur{"DA6"} = $rcur{"DG"} = $rcur{"DG6"} =
       $rcur{"DT"} = $rcur{"DC"} = 0.0;

	$_ =~ /^Detailed contributions for atom (.+):$/;  $idp = $1;
	($resname, $res, $atomname) = split(/:/, $idp, 3 );

	while(<>){
		if( $_ =~ /^ring: (\w+)\s+(\d+)\s+([-\.\d]+)/){
			$rcur{$1} += $3;
		}
		last if /^====/;
	}
	printf(OUT "%s\t%d\t%s\t%8.3f\t%8.3f\t%8.3f\t%8.3f\t%8.3f\t%8.3f\n",
       $resname, $res, $atomname, $rcur{"DA"}, $rcur{"DA6"}, $rcur{"DG"},
          $rcur{"DG6"}, $rcur{"DT"}, $rcur{"DC"} );

}

close OUT;
system( "sort -n -k2 -k3 < fozzoup" );
unlink( "fozzoup" );
