#!/bin/sh

echo "resname	res	atomname	ringcur	el	const	coil	pred	obs"
echo "6	3	4N	6	8N	8N	8N	8N	8N	8N"
awk 'NF==11 || NF==10{printf "%s\t%d\t%s\t%6.2f\t%6.2f\t%6.2f\t%6.2f\t%7.2f\t%7.2f\n", $2,$3,$4,$5,$6,$8,$9,$10,$11}' $1 > foouza
sort -k2n -k3 < foouza
/bin/rm foouza
