

test: duplex_test deform_test reflexive_test gsub_test hashed_test shifts_test \
	sff_test rattle_min_test gb_test xfin_test gbsa_test gb2_test \
	gb5_test gb8_test gb7_test rattle_md_test rembed_test dhfrndpmtx_test \
	asp_test aspnb_test prm_test cif_test xmin_test gbnetcdf_test \
	netcdf_test variable_14test \
	nmode1_test nmode2_test nmode3_test ips_test 

duplex_test::
	@./Run.duplex

deform_test::
	@./Run.deform

reflexive_test::
	@./Run.reflexive

gsub_test::
	@./Run.gsub

hashed_test::
	@./Run.hashed

shifts_test::
	@./Run.shifts

sff_test::
	@./Run.sff

rattle_min_test::
	@./Run.shake

fd_test:: 
	@./Run.fd

gb_test::
	@./Run.gb

gbnetcdf_test::
	@./Run.gbnetcdf

xfin_test::
	@./Run.xfin

gbsa_test::
	@./Run.gbsa

gb2_test::
	@./Run.gb2

gb5_test::
	@./Run.gb5

gb7_test::
	@./Run.gb7

gb8_test::
	@./Run.gb8

rattle_md_test::
	@./Run.rattle_md

dg_test::
	@./Run.dg

rembed_test::
	@./Run.rembed

dhfrndpmtx_test::
	@./Run.dhfrndpmtx

asp_test::
	@./Run.asp

aspnb_test::
	@./Run.aspnb

aspgb8_test::
	@./Run.aspgb8

variable_14test::
	@./Run.variable_14

crambin_test::
	@./Run.crambin

prm_test::
	@./Run.prm

cif_test::
	@./Run.cif

xmin_test::
	@./Run.xmin

netcdf_test::
	@./Run.netcdf

lmod_test::
	@./Run.lmod

nmode1_test::
	@./Run.nmode1

nmode2_test::
	@./Run.nmode2

nmode3_test::
	@./Run.nmode3

ips_test::
	@./Run.ips

pbsa_test::
	@./Run.pbsa

